site_name: Procedural Space Skybox
site_url: https://github.com/parallel-cascades/procedural-space-skybox-documentation

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Welcome Window: getting-started/welcome-window.md
  - Shader Skybox:
    - Shader Skybox Introduction: shader-skybox/introduction.md
    - Shader Skybox Setup: shader-skybox/setup.md
    - Customizing the Skybox Shader: shader-skybox/customization.md
    - Shader Properties Reference: shader-skybox/shader-properties-reference.md
    - Static Cubemap Rendering: shader-skybox/static-cubemap-rendering.md
    - Shader Skybox Troubleshooting: shader-skybox/troubleshooting.md
  - VFX Graph Skybox:
    - VFX Graph Skybox Introduction: vfx-graph-skybox/setup.md
    - VFX Graph Skybox Customization: vfx-graph-skybox/customization.md
    - Procedural Nebula Texture Generator: vfx-graph-skybox/procedural-nebula-texture-generator.md
  - Procedural Celestial Bodies:
    - Procedural Celestial Body Materials Introduction: procedural-celestial-bodies/procedural-celestial-body-materials-introduction.md
    - Procedural Stars: procedural-celestial-bodies/procedural-stars.md
    - Custom Menu Commands: procedural-celestial-bodies/custom-menu-commands.md
  - 3D Skybox Background: 3d-skybox-background.md
  - Changelog: changelog.md

theme:
  name: material
  logo: assets/logo.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://parallel-cascades.github.io/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ParallelCascades
    - icon: fontawesome/brands/github
      link: https://github.com/parallel-cascades

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - footnotes